### ISSUE TITLE
Incorrect constants value for mpegts stream type

### ISSUE THREAD

**Issue by trevd** [zaclimon/xipl#12]
In Tsutaeru/app/src/main/java/com/zaclimon/tsutaeru/util/Constants.kt
const val STREAM_TYPE_MPEG_TS = "mpeg_ts" should be "mpegts" or more often than not just "ts"
 Ideally you'd want to query the player_api.php to find out which stream types are valid for the account

**Comment by zaclimon** [comment]
Actually when the app was used for another provider using XtreamCodes, I got told that the correct values for streams were indeed mpeg_ts, hls and rtmp. Even when you check some providers setup guide, you can clearly see that the default output used is "mpeg_ts".

That said, I wasn't even aware of `player_api.php` so I might take a look at it when I'll update Tsutaeru for API 28. Thanks for the heads up! :+1:  

Looks like there's a little bit of docs there:

https://forum.xtream-codes.com/topic/3511-how-to-player-api-v2/

Also, btw next time, since it affects more Tsutaeru than xipl, it would be nicer if the issue was posted there instead. :stuck_out_tongue:

**Comment by trevd** [comment]
Apologises for that. I got a bit over excited. :) 

Yeah.. The api is quite nice and definitely worth implementing. I've just clone the project and have a dig around myself you may get the odd pull request. However I'm very much a Platform/OS C developer so I'll need to get upto speed on kotlin

Nice work tho, especially with the live channel integration :+1:

**Comment by zaclimon** [comment]
Haha no problem :p what I have for might look different since I using the api used in a provider's given app.

Ahh regarding Kotlin, if you get Java, then Kotlin will be a breeze :p. I wondering whether I should convert xipl to Kotlin as well. 

Let me know if there is something in the documentation that needs some cleanup. I know I have rushed that part a bit since there was Tsutaeru that can be used as an implementation.

**Comment by engalaaodeh** [comment]
hello,

supported for xtream codes v1.60 old version or not?

**Comment by zaclimon** [comment]
Hi! I can't really know since I don't have an Xtream Codes instance. Also, it would have been better to create a new issue for this instead of commenting on this one.

Closing this issue.
